language: php

php: ["5.4", "5.5", "5.6", "hhvm"]

matrix:
    allow_failures: [{"php": "5.6"}, {"php": "hhvm"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
