language: php

php: ["5.4", "5.5", "5.6", "hhvm", "hhvm-nightly"]

matrix:
    allow_failures: [{"php": "hhvm"}, {"php": "hhvm-nightly"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.6
    - secure: "BmzNkLUHoH70g6ClN4RuqxTKaS+FfchH99RhVV3gfr2o58Kt6NQGgcxoU2HkX1U5mNdBmIiz6n5aIMcV9L/hYiEXrkGkrYrXtLC01D7LmSNEyYb2OZ/mBWnKWlZN2EMZeGmnlsIHBqqIeFFLgh3lhIenSl3ia6jnoZmCdScuHWY="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
