language: php

php: ["5.4", "5.5", "5.6", "hhvm"]

matrix:
    allow_failures: [{"php": "5.6"}, {"php": "hhvm"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "ZK1dqeVXpWjlJGhHRi21bTs9FELBZBCDZoFu3wgJgUsG5gQL+GFnmsdXqs4RM8NSN9RRvPik5/ukiPtF/IiYo1DnnUbkdvUwu6ltPJ+ckugtI9t4QEq9GqJ/V0bqRcseYzPjbQLd64lT3shHuvKgMbp1HHH5Xs4NRHqhy4jsRms="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
